---
title: "Основная информация"
---

Здесь будет основная информация о блоке по R курса "Наука о данных"

Книжка с материалами: <https://pozdniakov.github.io/tidy_stats/>

## Расписание

| Лекция                | Семинар (группа 1)     | Семинар (группа 2)     |
|-----------------------|------------------------|------------------------|
| 12.04.2024 9:30-10:50 | 16.04.2024 13:00-14:20 | 18.04.2024 12:30-13:50 |
| 19.04.2024 9:30-10:50 | 23.04.2024 13:00-14:20 | 18.04.2024 12:30-13:50 |
| 26.04.2024 9:30-10:50 |                        |                        |
| 17.05.2024 9:30-10:50 |                        |                        |
| 24.05.2024 9:30-10:50 |                        |                        |
| ???                   |                        |                        |

: Расписание

## Система оценок

Оценка по курсу состоит из нескольких частей:

Тест на лекции (на 20 минут, 20 баллов) 1 домашнее задание (20 баллов, срок выполнения каждой в районе 2х недель) 5 лекций, 5 семинаров (по 1 баллу за активность)

-   одно бонусное домашнее задание на дополнительные + 5 баллов

Итого: максимум 50 баллов + 5 доп баллов

## Подготовка к курсу: установка R и RStudio

Для работы с R необходимо его сначала скачать и установить.

-   R
    -   [на Windows](https://cran.r-project.org/bin/windows/base/), найдите большую кнопку **Download R (номер версии) for Windows.**
    -   [на Mac](https://cran.r-project.org/bin/macosx/), если маку меньше, чем 5 лет, то смело ставьте \*.pkg файл с последней версией. Если старше, то поищите на той же странице версию для вашей системы.
    -   [на Linux](https://cran.rstudio.com/bin/linux/), также можно добавить зеркало и установить из командной строки:

<!-- -->

```         
sudo apt-get install r-cran-base
```

После установки R необходимо скачать и установить *RStudio*:

-   [RStudio Desktop](https://posit.co/download/rstudio-desktop/)

Если вдруг что-то установить не получается (или же вы просто не хотите устанавливать на компьютер лишние программы), то можно работать в облаке, делая все то же самое в веб-браузере:

-   [Posit Cloud (ранее -- RStudio Cloud)](https://posit.cloud)
