---
title: "Материалы курса"
---

## Лекция 1: Введение в R и RStudio {#sec-l1}

- Знакомство
- Почему R
- План модуля

- R как калькулятор, операторы
- Функции
- Присвоение переменных
- Векторы
- Векторизация
- Ресайклинг


## Семинар 1: Введение в R и RStudio {#sec-s1}

- Решение заданий на векторизацию и ресайклинг

## Лекция 2: Сложные структуры {#sec-l2}

- NA
- Логические векторы

- Матрицы
- Списки
- Датафреймы

## Семинар 2: Сложные структуры {#sec-s2}

- Задания на матрицы, списки и датафреймы

## Лекция 3: Установка пакетов и импорт данных, tidyverse {#sec-l3}

- установка пакетов
- импорт данных
- {skimr}
- RStudio проекты
- data.table vs tidyverse

## Семинар 3: Введение в tidyverse {#sec-s3}

- tidyverse intro: `select()`, `slice()`, `filter()`, `mutate()`

## Лекция 4: Продвинутый tidyverse {#sec-l4}

- tidyverse: аггрегация, *_join(), nested columns, `across()`, {purrr}

## Семинар 4: Продвинутый tidyverse {#sec-s4}

- задания на tidyverse: аггрегация, join, nested columns, `across()`


## Лекция 5: {ggplot2} {#sec-l5}

- Грамматика графики
- Зачем нужна грамматика
- Компоненты слоя: данные, геометрия, отображение эстетики, статистика, подгонка позиции
- Шкалы (scales)
- Координатные системы
- Фасетки
- Темы

## Семинар 5: {ggplot2} {#sec-s5}

- Строим графики

## Дополнительная лекция: Quarto {#sec-l6}

- Quarto

## Дополнительный семинар: Quarto / темы по запросу {#sec-s6}

- Практика Quarto
- Дополнительные темы по запросу